### ISSUE TITLE
Race condition everywhere

### ISSUE THREAD

**Issue by R-omk** [odan/cache#4]
I already use a similar approach to caching on heavy production and decided a few problems.

You should pay attention to the process of saving the cache.
It is necessary to use `opcache_invalidate()` with force option just before compilation. (Otherwise, the file may be in the old version for a while).

All this process must be in a critical section and covered with locks.
Only one process at a time must create and compile file, otherwise file may not be consistent at a time of compilation.
Also I independently monitor the size of free memory and do a `opcache_reset()` if necessary (use locks too).  

In addition, at compile time and file including I use `try catch Throwable` for catch inconsistent saved files with syntax problems.

**Comment by odan** [comment]
Hi @R-omk Thank you for your input. The question is where exactly in the codebase do you see an issue with race conditions? Could you please show me the affected parts of the code?

**Comment by R-omk** [comment]
The entire `set` function for a particular key must be atomic.  
Even in this case, reading the file may be incomplete and will cause a syntax error. (Handle this)

(Calling functions `opcache_compile_file` or `include` can happen (and will happen) after the start of the file saving by another process and before it is completed)

If one process took up locking, the best way out for other processes would be to simply skip saving the cache instead of waiting.
it is necessary to introduce some kind of  "Cache stampede" protection mechanism.

I in my own version do not allow simultaneous saving of any keys on the disk. Otherwise, this has a detrimental effect on disk performance. 

And look at `opcache_invalidate` because `opcache_compile_file` do not invalidate cache.

**Comment by odan** [comment]
I have tried to fix these issues. Can you take a look at the changes?

**Comment by odan** [comment]
Thank you for your really helpful hints and tips! 

IMHO If you're in a high-concurrency environment you should avoid using a filesystem cache (like this library). Multiple operations on the file system are very hard to make atomic in PHP.
