### ISSUE TITLE
How to set fileModifiedOffset?

### ISSUE THREAD

**Issue by gregoriopellegrino** [odan/cache#5]
Is it possible to set fileModifiedOffset? I see it is protected, is it a peculiar choice?

**Comment by odan** [comment]
The `fileModifiedOffset` property is just an "internal" setting to have a value high enough to make it work. The idea is that nobody should overwrite this value. Maybe `private` would be a better access modifier.

 Do you have to define another offset value?

**Comment by gregoriopellegrino** [comment]
I would like to set one year. The idea is to have a long-term cache for objects, that is regenerated when I update the object.

**Comment by odan** [comment]
The `fileModifiedOffset` value is only for OpCache that will only compile and cache files that are older than the script execution start time.

To define a TTL, you can already use the `$ttl` parameter of the `set` and `setMultiple` methods:

`public function set($key, $value, $ttl = null)`
`public function setMultiple($values, $ttl = null)`
